version: '3.6'

services:
  djaein_db:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: djaein
  djaein_django:
      build:
        context: ./djaein
        dockerfile: django.DockerFile
      command: python /app/manage.py migrate --noinput
      command: python /app/manage.py runserver 0.0.0.0:9001
      ports:
        - "9001:9001"
      volumes:
        - .:/app
      depends_on:
        - djaein_db
volumes:
  postgres_data:
